name: Deploy to GitHub Pages

# 當 push 到 main 分支時觸發
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 設定 Node.js 環境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # 使用 Node.js 版本（可以更改為你所需版本）

      # 3. 安裝依賴
      - name: Install dependencies
        run: npm install

      # 4. 建立 VitePress 頁面
      - name: Build VitePress site
        run: npm run docs:build

      # 5. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub 自動提供的 token
          publish_dir: ./docs/.vitepress/dist # 部署的目錄
          publish_branch: gh-pages # 要推送的分支
